name: devika_env
channels:
  - conda-forge
  - defaults
dependencies:
  - flask
  - flask-cors
  - toml
  - urllib3
  - requests
  - colorama
  - Jinja2
  - mistletoe
  - markdownify
  - pdfminer.six
  - playwright
  - pytest-playwright
  - tiktoken
  - ollama
  - openai
  - anthropic
  - google-generativeai
  - sqlmodel
  - keybert
  - GitPython
  - Markdown
  - xhtml2pdf
  - mistralai
  - Flask-SocketIO
  - eventlet
  - groq
  - orjson
  - gevent
  - gevent-websocket
  
  - pip
  - pip:
    - fastlogging
    - netlify-py
    - duckduckgo-search
    - curl_cffi
    
